"use client";

// ============================================================================
// Market Bubble Macintosh — demo content (chat, news, polymarket, read me)
// Flavor lifted from the real show content so the machine feels alive.
// ============================================================================
export const MacData = {
  CHAT_SEED: [
    { src: "tw", user: "degenmike", text: "this candle is actually unreal" },
    { src: "kk", user: "ansemfan", text: "gm everyone, we are SO back", role: "MOD" },
    { src: "x", user: "@whale_alerts", text: "another 9-figure wallet just woke up" },
    { src: "tw", user: "paperhands_pete", text: "sold the bottom again lol" },
    { src: "kk", user: "bullpen_betty", text: "ansem up +450% in two weeks is wild" },
    { src: "tw", user: "stacksonstacks", text: "buy the dip? or is this the dip before the dip" },
    { src: "x", user: "@polymarket", text: "Fed cut odds just moved to 62% on the board" },
    { src: "kk", user: "noiz_06_stan", text: "calling the top live takes guts", role: "VIP" },
    { src: "tw", user: "banks", text: "invest in yourself first" },
    { src: "x", user: "@MarketBubble", text: "Live Thursday 1PM. Bring your bags." },
  ],
  CHAT_AMBIENT: [
    "chart looking like the alps rn",
    "who else watching from work",
    "my exit liquidity arrived",
    "1929 vibes but in a fun way",
    "the tape never lies",
    "ok that wick was personal",
    "someone check on the shorts",
    "printing. absolutely printing.",
    "this is financial entertainment btw",
    "ring the bell already",
    "banks just muted the wrong mic again",
    "chat speedrunning a margin call",
    "my wife thinks this is a cooking show",
    "DO NOT check your portfolio rn",
    "the bubble machine in the corner is a top signal",
    "ansem typing... everyone hold",
    "i was told there would be gains",
    "sir this is a casino",
    "new candle just dropped",
    "fed meeting bingo card ready",
    "bought the top so you don't have to",
    "liquidity? i hardly know her",
  ],
  NEWS: [
    { h: "Bitcoin reclaims $68K as funding flips positive", m: "CoinDesk · 5m ago" },
    { h: "Fed-cut odds jump to 62% on Polymarket", m: "Bloomberg · 22m ago" },
    { h: "Solana ETF filings stack up on record inflows", m: "The Block · 1h ago" },
    { h: "Hyperliquid volume tops the perp leaderboard again", m: "The Defiant · 2h ago" },
    { h: "AI tokens rally as inference costs fall", m: "Reuters · 3h ago" },
    { h: "Mike Majlak crashes out on marathon show segment", m: "The Bubble Dispatch · 4h ago" },
  ],
  NEWS_WIRE: [
    { h: "Whale moves 40,000 BTC after four years dormant", m: "Whale Alert" },
    { h: "Memecoin index up 19% as 'fart season' declared", m: "The Bubble Dispatch" },
    { h: "Exchange outage strands traders mid-candle", m: "CoinDesk" },
    { h: "Polymarket whale bets $2.1M on September cut", m: "Bloomberg" },
    { h: "Ansem's bullpen pick triples in 48 hours", m: "The Bubble Dispatch" },
    { h: "Treasury yields slip; risk assets catch a bid", m: "Reuters" },
    { h: "Dogecoin ETF rumor denied, then un-denied", m: "The Block" },
    { h: "Banks: 'we are not financial advisors, obviously'", m: "The Bubble Dispatch" },
    { h: "Funding rates hit 3-month high as longs pile in", m: "The Defiant" },
    { h: "Retail is back: brokerage signups hit '21 levels", m: "WSJ" },
  ],
  POLY: [
    { q: "Fed cuts rates in September?", yes: 62 },
    { q: "BTC above $80K by July 31?", yes: 34 },
    { q: "ETH flips $4K this month?", yes: 27 },
    { q: "Ansem wins the Bullpen trading comp?", yes: 71 },
    { q: "New ATH for SOL in 2026?", yes: 48 },
  ],
  TICKERS: [
    { sym: "BTC", price: 68421 },
    { sym: "ETH", price: 3580 },
    { sym: "SOL", price: 172.3 },
    { sym: "HYPE", price: 38.6 },
    { sym: "DOGE", price: 0.164 },
    { sym: "NVDA", price: 1204 },
  ],
  MAIL: [
    {
      id: "welcome",
      from: "The Management",
      subj: "Welcome to the bubble",
      body: "New tenant,\n\nThe machine is yours. The show opens itself \u2014 that is not a bug, that is the point.\n\nHouse rules: feed the cat (clicking counts), do not open the folder marked Do Not Open, and anything you make in Bubble Trader is pretend. The feeling of getting liquidated, however, is real.\n\nRead Me has the secrets.\n\n\u2014 Mgmt",
    },
    {
      id: "margin",
      from: "Bubble Trader Desk",
      subj: "NOTICE OF MARGIN CALL (pretend)",
      body: "Dear valued degenerate,\n\nThis letter is to inform you that at some point you will trade the house money to zero. When that happens, a fresh $10,000 will be wired in, no questions asked, because none of this is real.\n\nWe note for the record that 20x leverage was YOUR idea.\n\n\u2014 The Desk",
    },
    {
      id: "expense",
      from: "Accounts Payable",
      subj: "RE: Expense report \u2014 DENIED",
      body: "Re: reimbursement claim #1929 \u2014 'industrial bubble machine, stage left.'\n\nDenied. The bubble machine is load-bearing scenery and therefore capital expenditure, not entertainment. Resubmit under 'set dressing' and it sails through.\n\nAlso the cat's salary is overdue again.\n\n\u2014 AP",
    },
    {
      id: "cat",
      from: "Facilities",
      subj: "RE: RE: the cat",
      body: "To whom it may concern,\n\nThe cat is not 'unauthorized personnel.' The cat was here before the desk, the machine, and arguably the market itself. The cat stays.\n\nPlease stop filing tickets about the cat.\n\n\u2014 Facilities",
    },
    {
      id: "review",
      from: "The Management",
      subj: "Your weekly performance review",
      body: "Summary of trading week:\n\n\u2022 Conviction: high\n\u2022 Entries: early\n\u2022 Exits: emotional\n\u2022 Snacks consumed at desk: a number we will not print\n\nOverall: it's still early. See you Thursday, 1PM.\n\n\u2014 Mgmt",
    },
  ],
};
